language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: cRZoKLK5lUUdB3DoIrunqx7IStc4WxVCRAiuhAXQMf/BB/LgVwfUMOVd0XiNBQaDMRllS/6gUB+DDX6L43RCkubwFbJXewuZ4I79l9pklPxtO9X0RKpfOYiLNQt8TTXEC3Fg1CMYJ5ssvJXZ8svJxlAezYrtQd0Y4u6fFeuAqVMV0kpWa8eBiencqOZn6kT3ySZDA3vrPx055OncDusp7ncJ4zMgwGmJgqgnyUCEKIWUuK6ta4WrFku3C6qSsJYbdzhaGow3jLVa5+8tbGjszPGCYQk7f6fAA0WG72zVIAk7djJsBPXYCCCNHwmPpUBv/tM9eBwNgYefVc/p06FRmHGnfFJwgsL4puEhGPG+fnxMsTNAmQRuYduDDNflpREw1fSbUJKD3JrnYrtCl1A6VSUPtAR4U0DEiVpA8d/96Gb3KHASCtEV8uwand1lbmW1xhN79ihULq2Hl1LuM582zFVWbAdnY9/59wewBmuXJTKd4Rl8+bPFz6TJaEQeqm775zXv9i9qkhcgkNKy5IFeylUFOsZIgcmPOMt3GI0xtOFy2XnuwbOSvCe9tcPDuWNV6GrPtT3AY71j2A+TeZYQ6k/Oa2YnJrTiXZDftk0cp0nX3fDY0lLoSMhaIHo0qjRlzkMBnD0md1BEUXtk0fGRmQOz5hWJgZfP5pTqJ55P7vk=
